# @package _global_
defaults:
- r1pro
- override /data: cleaned_batteries_0919
- _self_

# 117,689 frames; 8 ranks x 16 samples; 920 steps/epoch.
# Distributed sampler pads 7 samples; last batch is 8 per rank.
checkpointing_steps: 920
eval_steps: 920
batch_size_val: 4
datastatics_path: /mnt/cfs/7rnh3z/kele/0919/mt/cleaned_batteries/training/g05/dataset_stats.json
resume_ckpt: null
logger:
  mode: offline
  log_steps: 1
model:
  pretrained_ckpt: /mnt/cfs/7rnh3z/kele/GalaxeaVLA/base_checkpoint/g05-base/checkpoints/model_state_dict.pt
  use_pretrained_norm_stats: false
  enable_bf16_training: true
  batch_size: 16
  grad_accumulation_steps: 1
  num_workers: 8
  prefetch_factor: 2
  max_epochs: 10
  max_steps: null
  model_arch:
    hf_processor_path: /mnt/cfs/7rnh3z/kele/GalaxeaVLA/base_checkpoint/qwen3_5_2b_base_processor
tokenizer:
  vq_config:
    ckpt_dir: /mnt/cfs/7rnh3z/kele/GalaxeaVLA/base_checkpoint/action_tokenizer.pt
    dropout_noop_parts: true
